function Stat({ label, value, suffix, icon, trend, positive, warning, danger }) {
  return <article className="stat-card"><div className={`stat-icon ${warning ? 'yellow' : danger ? 'red' : ''}`}>{icon}</div><p>{label}</p><h2>{Number(value || 0).toLocaleString()} <small>{suffix}</small></h2><span className={positive ? 'trend positive' : warning ? 'trend warning' : 'trend danger'}>{trend}</span></article>
}

function SellerDashboard({ dashboard, isLiveDashboard, setPage, showNotice, onAddProduct }) {
  const categoryEntries = Object.entries(dashboard.availableStockByCategory || {})
  const maxCategoryStock = Math.max(1, ...categoryEntries.map(([, amount]) => amount))
  return <div className="page-content">
    <section className="welcome-row"><div><p className="eyebrow">WHOLESALE SELLER DASHBOARD</p><h1>Grow your farm <i>business.</i></h1><p className="subtle">List harvest lots, set your minimum order and sell directly to serious buyers.</p></div><button className="primary-button" onClick={onAddProduct}>List bulk produce</button></section>
    <section className="hero-banner wholesale-banner"><div className="hero-copy"><span className="pill">DIRECT FARM TRADE</span><h2>Your harvest. <i>Your terms.</i></h2><p>Build long-term supply relationships with retailers, hotels, processors and fellow farmers.</p><div className="hero-actions"><button onClick={onAddProduct}>Create a bulk listing <span>-&gt;</span></button><button className="ghost-hero-button" onClick={() => setPage('marketplace')}>View buyer board</button></div><div className="trade-proof"><span>Verified farm supply</span><span>Bulk lots</span><span>Direct negotiation</span></div></div><img src="https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1400&q=85" alt="Farmer working in a green field" /></section>
    <section className="stat-grid"><Stat label="Available to sell" value={dashboard.totalAvailableStock} suffix="units" icon="*" trend="Ready for wholesale" positive /><Stat label="Committed stock" value={dashboard.totalReservedStock} suffix="units" icon="o" trend="For buyer orders" positive /><Stat label="Lots needing attention" value={dashboard.lowStockProducts} suffix="lots" icon="!" trend="Update availability" warning /><Stat label="Sold-out lots" value={dashboard.outOfStockProducts} suffix="lots" icon="x" trend="Relist next harvest" danger /></section>
    <section className="dashboard-grid"><div className="panel stock-panel"><div className="panel-heading"><div><p className="eyebrow">INVENTORY ANALYTICS</p><h3>Stock by category</h3></div><button className="text-button" onClick={() => setPage('inventory')}>Full inventory -&gt;</button></div><div className="chart-area">{categoryEntries.map(([category, amount], index) => <div className="bar-group" key={category}><span className="bar-value">{amount}</span><div className={`bar bar-${index}`} style={{ height: `${Math.max(28, (amount / maxCategoryStock) * 142)}px` }} /><span className="bar-label">{category}</span></div>)}</div></div>
      <div className="panel health-panel"><div className="panel-heading"><div><p className="eyebrow">SUPPLY READINESS</p><h3>Wholesale capacity</h3></div><span className="live-dot">{isLiveDashboard ? 'Live API' : 'Demo data'}</span></div><div className="pulse-number">{dashboard.averageStock}<small> avg. units / listing</small></div><div className="progress-line"><span style={{ width: '73%' }} /></div><div className="health-labels"><span>{dashboard.minimumStock} min</span><span>{dashboard.maximumStock} max</span></div><div className="health-note"><span>*</span><p>Your supply is <strong>ready to trade</strong>. Keep quantities current for buyer confidence.</p></div></div>
    </section>
    <section className="panel alert-panel"><div className="panel-heading"><div><p className="eyebrow">LISTING HEALTH</p><h3>Lots to update before buyers ask</h3></div><button className="text-button" onClick={() => setPage('inventory')}>Manage stock -&gt;</button></div><div className="alert-list">{dashboard.lowStockItems.map((item) => <div className="alert-row" key={item.productId}><div className="product-dot">{item.productName.charAt(0)}</div><div className="item-name"><strong>{item.productName}</strong><small>{item.category}</small></div><span className={item.availableQuantity === 0 ? 'stock-badge empty' : 'stock-badge'}>{item.availableQuantity === 0 ? 'Sold out' : `${item.availableQuantity} units left`}</span><button onClick={() => showNotice(`${item.productName} is ready to update.`)}>Update lot</button></div>)}</div></section>
  </div>
}

export default SellerDashboard
